### ISSUE TITLE
What's the patten to when we use a light screen and a (navy) dark screen?

### ISSUE THREAD

**Issue by giljulio** [transferwise/neptune#16]
I've heard hypothesis such as: 

- It's used at the end to show completion of an action
- It's used at the start and end to should beginning and completion of a flow

but then it's also shown at intro screen before login, currency selector and invite screen

**Comment by twlleon** [comment]
The [background and work ](https://transferwise.atlassian.net/wiki/spaces/SM/pages/1122699194/Blue+Screens?atlOrigin=eyJpIjoiMjhjNGQyMWE3N2ZlNGIxZGIwOWQwOWQzOTEyNWE5MTYiLCJwIjoiYyJ9)around blue screens 

**Highlighted problems:** 
- The “success” screen pattern has been abused over time and now seems to lack any real logic. 
- The layout is different depending on the flow (We've just achieved a parent component for blue screens on iOS)
- Blue screens used to be just the success screens, created with the reasoning that since the rest of the app is light, we bring more attention to these important screens with contrast. Since nobody owned blue screens, they’ve been used whenever a team decides a screen is important. Which has sprouted the other group - alerts and info screens.
- Depending on platform and flow, we use different illustrations, with different sizes.
- The CTA pattern used throughout these screens is all over the place (we worked on defining some rules)

My suggestion is based on the above to achieve a more cohesive way of developing and using blue screens. 

**I believe we're seeing 3 types of screens (based on intent):** 


**Success Screen/Component** | A type of screens/components that  - celebrate the completion of a high-level flow eg transfer flow eg send money, top up, card order. Anything the user has specifically decided to do and has completed.  
This excludes flows that are side-products of a high level decision eg verification, rate watching etc. 

These screens value having a starker contrast from other screens, so their background could differ (could be Navy Mid or maybe something else as long as it’s accessible). 

[Potential rules](https://www.figma.com/file/XPSkodp82698fXUljUoTA8/Blue-screens-Setting-up-screens?node-id=420%3A723)
Since these screens will always be at the end of the flow, users can only either close the flow or continue with a new flow (repeat transfer, share with friends) 
  In these screens  
- we don’t use close icons (needs two hands to close, has no context to where the closing leads)
 - Closing/Dismissive action is represented by a CTA  (lessening the amount of funnels that are created)
- This screen never has more than 2 CTAs, in that case it’s valid to look at using a regular screen or revisiting the amount actions. 
- Has a valid case to differ, hence have a blue background.

-- | --

**Info Screen/Component** | A type of screens/components that  - introduce features, potential limitations or important processes eg end-to-end verification, nearby payments, updating details etc

We’ve seen trends of white background views being used. I believe many of these information screens work better with a white background since they tend to be a flow that exist within a flow and it would feel more cohesive for those to not have a contrasted background. 

[Potential rules](https://www.figma.com/file/XPSkodp82698fXUljUoTA8/Blue-screens-Setting-up-screens?node-id=420%3A506): 
Since these screens participate in a flow they will always have a  
- Back arrow (no close icon) 
- At least one CTA to continue the flow 
- The background is white

-- | --

**Alert Screen/Component** | It’s a type of screens/components that  - act as notifications or errors and will be shown without the user choosing to see it. 
Eg holiday notices, various errors, up-sells to features 

This grouping doesn’t necessarily need to have disruptive full view screens, since the low level importance of seeing them might cause frustration.

[Potential rules](https://www.figma.com/file/XPSkodp82698fXUljUoTA8/Blue-screens-Setting-up-screens?node-id=418%3A1330)
These screens exist on their own, triggered by an external or internal system action.  
- Thus they won’t include a back or close icons - it would be a duplication.  
- 1 CTA - to affirm and acknowledge   
- 2 CTAs - to confirm or dismiss
- We could use either snackbars or other similar solutions to create a non-disruptive experience. If a full screen is needed to call attention (eg security) it would be contrasting (blue).

**Comment by twlleon** [comment]
@synchromation  @juhanh @gusso

**Comment by giljulio** [comment]
@twlleon seems like there is a large overlap between "alert screen" and "info screen". One could argue that holiday notice is "info", and therefore should be light themed. 

I feel the reason it's got out of hand is that the rules are just too complex. An alternative I'd suggest, is to drop dark themes on all but success screens (end of flow). If we mix concepts such as "it's to show completion" but also to "call attention" - I don't think the user will subconsciously understand

**Comment by twlleon** [comment]
To answer your initial question - we don't have rules around when light or navy screens are used. There have been no rules to blue screens for a while which is why we're where we are with this. @giljulio 

I was actually just proposing some rules, starting from understanding the types of screens we have, giving examples and setting tules to their layouts. Essentially figuring out the patterns. Which is why the description is more complex - I'm ideating wether even success screens should/shouldn't have blue backgrounds. 'Success screens' itself is a very loose term, so I'm also defining that. 

But to continue, yes what I'm proposing is that Success screens for now would be the only screens other than Security related alert screens to have a blue background. Anything that exists as an entry point/finish to a flow within a flow, would be white. And overall, if the feedback content is sparse, the info not relevant enough to disrupt users, let's use snackbars or something similar (hence the reference to "components" ).

**Comment by giljulio** [comment]
Don't get me wrong - I think it's great that you have grouped the different types of navy themed screens we have, and also, the rules that we should follow 👍 

Overall we are very much in agreement. I actually think relying on colour contrast to convey a message/importance is a bit dangerous as this concept of white and navy screens are redundant in 🌑dark mode & high contrast mode. Also, another concern I have, I don't think it's great for accessibility due to the eye needing to invert what colour to look for on the screen - I don't think it's a deal breaker, especially if we use it sparingly but we should consider it.

> But to continue, yes what I'm proposing is that Success screens for now would be the only screens other than Security related alert screens to have a blue background. Anything that exists as an entry point/finish to a flow within a flow, would be white. 

How come you feel that Security related alerts should be navy themed? 

> And overall, if the feedback content is sparse, the info not relevant enough to disrupt users, let's use snackbars or something similar (hence the reference to "components" ).

Yep agree

**Comment by twlleon** [comment]
I think you're right @giljulio, we do quite agree on this. I'll try to elaborate more on this. 

**Colour contrast to highlight screens** - It's essentially the reasoning that started the problem. Let's put it like this, I would consider keeping these screens as 'blue' for the current stage of us moving to a common master layout for those screens. Saying that they wouldn't have a coloured background, or it would need to be another colour, needs more research - When we start redesigning success screens at the end of March we will make a more educated decision on what those screens will look like, what the background colour is or isn't. 

**By white screens**, I meant the environment background (in dark mode it would be dark, in default it would be white) The distinction I'm making is also that Info screens need a different master component from 'Blue screens' to for example keep people from adding the 'X' icon to these screens. 

> How come you feel that Security related alerts should be navy themed?

I'm considering that this is the only team that could have the pass for adding full screen alerts at this point on. Their new blue screens are built on our master Blue Screen layout which makes it related to the Success screens - the same background colour will be used across those screens. So when we make a decision on Success screens, we'll have a decision on full screen alerts.

**Comment by anttio** [comment]
Closing and moving to JIRA.
